### ISSUE TITLE
Matrix dimensions do not agree

### ISSUE THREAD

**Issue by vbern** [XiaoleiLiuBio/MVP#27]
I added my data using the MVP.data function. I've confirmed that the output files all have the same n value, but when I run the following code, I get a Matrix dimensions error. This error does not occur if I run the model without PCs. 
I noticed in the MVP readme, that the Covariate lines were commented out. Is this a problem with the underlying packages?

```
MVP.Data(fileHMP="data/filtered.hmp.txt",
         filePhe="data/mvp_input_20180511.txt",
         sep.hmp="\t",
         sep.phe="\t",
         SNP.effect="Add",
         fileKin=T,
         filePC=T,
         out="mvp"
)

genotype <- attach.big.matrix("mvp.geno.desc")
phenotype <- read.table("mvp.phe",head=TRUE)
map <- read.table("mvp.map" , head = TRUE)
Kinship <- attach.big.matrix("mvp.kin.desc")
Covariates <- attach.big.matrix("mvp.pc.desc")
```

```
for(i in 2:ncol(phenotype)){
  chiles_env_pcs <- MVP(
    phe=phenotype[, c(1, i)],
    geno=genotype,
    map=map,
    K=Kinship,
    CV.GLM=Covariates,
    CV.MLM=Covariates,
    CV.FarmCPU=Covariates,
    nPC.GLM=5,
    nPC.MLM=3,
    nPC.FarmCPU=3,
    perc=1,
    priority="memory",
    ncpus=2,
    vc.method="GEMMA",
    maxLoop=10,
    method.bin="FaST_LMM",#"FaST-LMM","EMMA", "static"
    threshold = 1.895353e-06,
    method=c("GLM", "MLM", "FarmCPU")  )
}
```

The Error Message:
```
[1] "Input data has 190 individuals, 30418 markers"
[1] "Principal Component Analysis Start..."
 means for first 10 snps:
 [1] 0 0 0 0 0 0 0 0 0 0
Error in SetElements.bm(x, i, j, value) : 
  Matrix dimensions do not agree with big.matrix instance set size.
```

**Comment by hyacz** [comment]
The covariate lines is commented out because we don't want the user to join easily before understanding it, which can make the result worse.

Error in SetElements.bm means that there is something wrong with the bigmemory package, like an array out of bounds. I will check for bugs in the code later, but before that I have to point out that there is a problem with your usage.

1. The covariate that MVP considers is to remove other covariates from the PC. If nPC.model > 0, the PC will be automatically calculated and added to the corresponding model.

2. The value passed in the threshold parameter will pass the Bonferroni correction and then be the final displayed threshold (final threshold = threshold / number of marker). Usually we will use 0.05 or 0.01.

Your code can be rewritten as follows:
```
MVP.Data(fileHMP="data/filtered.hmp.txt",
         filePhe="data/mvp_input_20180511.txt",
         sep.hmp="\t",
         sep.phe="\t",
         SNP.effect="Add",
         fileKin=T,
         filePC=F,
         out="mvp"
)

genotype <- attach.big.matrix("mvp.geno.desc")
phenotype <- read.table("mvp.phe",head=TRUE)
map <- read.table("mvp.map" , head = TRUE)
Kinship <- attach.big.matrix("mvp.kin.desc")

for(i in 2:ncol(phenotype)){
  chiles_env_pcs <- MVP(
    phe=phenotype[, c(1, i)],
    geno=genotype,
    map=map,
    K=Kinship,
    nPC.GLM=5,
    nPC.MLM=3,
    nPC.FarmCPU=3,
    perc=1,
    priority="memory",
    ncpus=2,
    vc.method="GEMMA",
    maxLoop=10,
    method.bin="FaST_LMM",
    threshold = 0.05,
    method=c("GLM", "MLM", "FarmCPU")  )
}
```

**Comment by hyacz** [comment]
It was closed because it was not updated in a month. Feel free to open if you have a question, or submit a new issue.
